### ISSUE TITLE
ダッシュボードのデザイン

### ISSUE THREAD

**Issue by yukikamome316** [yukikamome316/alcoho-rhythm#26]
以下の Issue に対応する画面のデザイン案があると、開発がスムーズに進みそう
- #2 
- #18

**Comment by hana-rs** [comment]
![スクリーンショット 2024-11-24 001258](https://github.com/user-attachments/assets/de94dd60-332d-4c4b-a27b-931b15c426ad)
とりあえず、
・飲酒量データをStacked Bar Chartでもって、棒グラフの色は体調ごとに変化させて(Chart.jsのページがランダム生成されてしまう関係でわかりやすく画像は一色のみにしてます)、体調ごとの限界アルコール量をそこに線引きする
・体調平均値、飲酒回数、(健康飲酒率(空白埋めに適当に考えたやつですが、例えば体調が2以下だったものを「健康」として、月の健康率がどのくらいだったかを健康飲酒率とする))を数字で表示する
・どの体調がどのくらいの割合で存在していたかをPieチャートで表示する
などできたらいいかなーと思っています。
この下は、限界アルコール摂取量の計算画面になるんですが、Discordで言ったように、Registerの使いまわしでこちらがシミュレーションできるような画面にするのはどうですか？

**Comment by hana-rs** [comment]
あと、なんか配置下手なのかどうしても右下スペース余っちゃうので、なにかいい案があればください

**Comment by hana-rs** [comment]
そもそも数字表示の部分って、データ持ってこれますか？？

**Comment by yukikamome316** [comment]
> そもそも数字表示の部分って、データ持ってこれますか？？

持ってこれる！

**Comment by hana-rs** [comment]
![スクリーンショット 2024-11-25 000358](https://github.com/user-attachments/assets/f273b340-9078-468a-ba0b-7d002194c15a)
![スクリーンショット 2024-11-25 000409](https://github.com/user-attachments/assets/65262fc9-2b6c-44e7-aaf1-dbaa6014efef)

**Comment by hana-rs** [comment]
余白できちゃってた部分なんですけど、
5段階の体調ごとの純アルコール量を乗せるのはどうでしょうか？
下のシミュレーションのとき参考になるかなーと思ってのせてみました

シミュレーションは、「シミュレーションで計算された純アルコール量と一番近い体調の数値を表示する」という前提でデザインしました。できるか分からないですがデザインなので適当にやってみました。
健康飲酒(体調2のときの純アルコール量)までの純アルコール量カウントダウンがあれば、組み合わせをいろいろ試してもらえるかなと思い載せてみました。
健康飲酒に近づくための参考として、ビールとハイボールの純アルコール量を載せてみました。

**Comment by yukikamome316** [comment]
いいね！全体的に情報が集約されてて使いやすそう
強いて言うなら、ユーザーが最も知りたい情報は体調平均値・予測値だから、他の要素よりも目立たせるべきかなと思った！

**Comment by hana-rs** [comment]
![スクリーンショット 2024-11-25 231711](https://github.com/user-attachments/assets/551b73b7-a64b-46f1-98af-8c7a929c66bd)
上だけですが、こんな感じはどうですか？

**Comment by yukikamome316** [comment]
> 上だけですが、こんな感じはどうですか？

LGTM
あとは体調の値なんだけど、1が良いのか5が良いのかぱっと見わからないと思うから、「体調の値」という表現を避けるといいかもしれない

**Comment by hana-rs** [comment]
![スクリーンショット 2024-11-26 001701](https://github.com/user-attachments/assets/21457276-ba0d-4e3c-93e9-cce4e40a2651)

**Comment by yukikamome316** [comment]
> ![スクリーンショット 2024-11-26 001701](https://private-user-images.githubusercontent.com/132898015/389589184-21457276-ba0d-4e3c-93e9-cce4e40a2651.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MTc1OTAsIm5iZiI6MTczMjYxNzI5MCwicGF0aCI6Ii8xMzI4OTgwMTUvMzg5NTg5MTg0LTIxNDU3Mjc2LWJhMGQtNGUzYy05M2U5LWNjZTRlNDBhMjY1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQxMDM0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjY2NjgwM2ExNWI0ZmMxZDZhM2JiMjBiNDkzNzJiMjdiODhkYTk3NTYzMGIxYTMzMjk2ZWIyYTE3NjBhOWYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lxgKbq5SXLxUt6GWUyQV7QVNxCojyv5i-cFkIcRlS1U)

いいね、これでいこう

**Comment by yukikamome316** [comment]
@hana-rs 
Figma共有してもらえないかな？

**Comment by hana-rs** [comment]
> @hana-rs Figma共有してもらえないかな？

了解です、少々お待ちくださいー
